version: "3"
services:
    lunchctf_satsmt: 
        build: .
        container_name: lunchctf_satsmt
        entrypoint: /bin/bash
        environment:
            - discovery.type=single-node
        security_opt:
            - seccomp:unconfined
            - apparmor:unconfined
        stdin_open: true
        tty: true
        volumes:
            - ./src/:/lunchctf_satsmt/
